services:
  db:
    image: mysql:8.0
    container_name: finshift-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - finshift_db_data:/var/lib/mysql
    ports:
      - "3308:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: finshift-wp
    restart: always
    ports:
      - "8002:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'local');
        define('WP_DEBUG', true);
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - finshift_wp_data:/var/www/html

volumes:
  finshift_db_data:
  finshift_wp_data:
